import './globals.css'
import Head from 'next/head'


export const metadata = {
    title: '四人纸牌-找朋友',
    description: 'Generated by create next app',
    appleWebApp: {},
    icons: {
        icon: ['/apple-icon.png'],
        apple: ["/apple-icon.png"]
    },
    manifest: "/manifest.json",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <link rel="apple-touch-icon" href="/apple-icon.png" />
            <body className="game-body">
                {children}
            </body>
        </html>
    )
}
