import './globals.css'


export const metadata = {
    title: '四人纸牌-找朋友',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="game-body">
                {children}
            </body>
        </html>
    )
}
